import type { CmsBlockDefinition, CmsBlockType, CmsFieldDefinition } from "./types";

const surfaceField: CmsFieldDefinition = {
  key: "surface",
  label: "Use mist background",
  kind: "boolean",
  defaultValue: false,
};

const linkFields: CmsFieldDefinition[] = [
  { key: "label", label: "Link label", kind: "text" },
  { key: "url", label: "Link URL", kind: "url" },
];

const cardFields: CmsFieldDefinition[] = [
  { key: "eyebrow", label: "Small label", kind: "text" },
  { key: "status", label: "Status", kind: "text" },
  { key: "title", label: "Title", kind: "text" },
  { key: "body", label: "Summary", kind: "textarea" },
  { key: "detail", label: "Additional detail", kind: "textarea" },
  { key: "imageUrl", label: "Image URL", kind: "url" },
  { key: "imageAlt", label: "Image alternative text", kind: "text" },
  {
    key: "focusX",
    label: "Horizontal image focus (%)",
    kind: "number",
    defaultValue: 50,
    help: "0 is left, 50 is centre and 100 is right.",
  },
  {
    key: "focusY",
    label: "Vertical image focus (%)",
    kind: "number",
    defaultValue: 50,
    help: "0 is top, 50 is centre and 100 is bottom.",
  },
  { key: "linkLabel", label: "Link label", kind: "text" },
  { key: "linkUrl", label: "Link URL", kind: "url" },
];

const imageFields: CmsFieldDefinition[] = [
  { key: "imageUrl", label: "Image URL", kind: "url" },
  { key: "imageAlt", label: "Alternative text", kind: "text" },
  { key: "caption", label: "Caption", kind: "text" },
  { key: "rightsHolder", label: "Rights holder", kind: "text" },
  {
    key: "focusX",
    label: "Horizontal image focus (%)",
    kind: "number",
    defaultValue: 50,
    help: "0 is left, 50 is centre and 100 is right.",
  },
  {
    key: "focusY",
    label: "Vertical image focus (%)",
    kind: "number",
    defaultValue: 50,
    help: "0 is top, 50 is centre and 100 is bottom.",
  },
  { key: "linkUrl", label: "Optional link URL", kind: "url" },
];

export const cmsBlockDefinitions: CmsBlockDefinition[] = [
  {
    type: "hero",
    label: "Home hero",
    description: "Large opening area with logo or image and two actions.",
    fields: [
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "lead", label: "Lead text", kind: "textarea" },
      { key: "statusText", label: "Status line", kind: "text" },
      { key: "imageUrl", label: "Image URL", kind: "url" },
      { key: "imageAlt", label: "Image alternative text", kind: "text" },
      { key: "primaryLabel", label: "Primary button label", kind: "text" },
      { key: "primaryUrl", label: "Primary button URL", kind: "url" },
      { key: "secondaryLabel", label: "Secondary button label", kind: "text" },
      { key: "secondaryUrl", label: "Secondary button URL", kind: "url" },
    ],
    defaultData: {
      eyebrow: "ENDOFACE · by ISEFS",
      title: "Page title",
      lead: "Introductory text",
      statusText: "",
      imageUrl: "",
      imageAlt: "",
      primaryLabel: "Learn more",
      primaryUrl: "/about",
      secondaryLabel: "",
      secondaryUrl: "",
    },
  },
  {
    type: "page_header",
    label: "Page header",
    description: "Standard page title with eyebrow and introductory text.",
    fields: [
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "lead", label: "Lead text", kind: "textarea" },
    ],
    defaultData: { eyebrow: "Section", title: "Page title", lead: "" },
  },
  {
    type: "split_text",
    label: "Heading and text",
    description: "Two-column section with heading and paragraphs.",
    fields: [
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "paragraphs", label: "Paragraphs", kind: "string_list" },
      { key: "linkLabel", label: "Link label", kind: "text" },
      { key: "linkUrl", label: "Link URL", kind: "url" },
      surfaceField,
    ],
    defaultData: {
      eyebrow: "",
      title: "Section title",
      paragraphs: ["Section text"],
      linkLabel: "",
      linkUrl: "",
      surface: false,
    },
  },
  {
    type: "card_grid",
    label: "Card grid",
    description: "Responsive collection of cards for activities, benefits or categories.",
    fields: [
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "intro", label: "Introductory text", kind: "textarea" },
      {
        key: "columns",
        label: "Desktop columns",
        kind: "select",
        options: [
          { label: "Two", value: "2" },
          { label: "Three", value: "3" },
          { label: "Four", value: "4" },
        ],
      },
      { key: "items", label: "Cards", kind: "item_list", itemFields: cardFields },
      { key: "footer", label: "Footer note", kind: "textarea" },
      { key: "linkLabel", label: "Section link label", kind: "text" },
      { key: "linkUrl", label: "Section link URL", kind: "url" },
      surfaceField,
    ],
    defaultData: {
      eyebrow: "",
      title: "Card section",
      intro: "",
      columns: "3",
      items: [],
      footer: "",
      linkLabel: "",
      linkUrl: "",
      surface: false,
    },
  },
  {
    type: "list",
    label: "Structured list",
    description: "Heading, introduction, list items and optional footer.",
    fields: [
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "intro", label: "Introductory text", kind: "textarea" },
      { key: "items", label: "List items", kind: "string_list" },
      { key: "footer", label: "Footer note", kind: "textarea" },
      surfaceField,
    ],
    defaultData: {
      eyebrow: "",
      title: "List title",
      intro: "",
      items: ["List item"],
      footer: "",
      surface: false,
    },
  },
  {
    type: "notice",
    label: "Notice",
    description: "Highlighted status or explanatory notice.",
    fields: [
      { key: "status", label: "Status label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "body", label: "Text", kind: "textarea" },
      surfaceField,
    ],
    defaultData: { status: "Information", title: "", body: "Notice text", surface: false },
  },
  {
    type: "event_feature",
    label: "Event feature",
    description: "Prominent event or course information with external link.",
    fields: [
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "status", label: "Status", kind: "text" },
      { key: "title", label: "Section title", kind: "text" },
      { key: "body", label: "Section text", kind: "textarea" },
      { key: "eventTitle", label: "Event title", kind: "text" },
      { key: "meta", label: "Date and location", kind: "text" },
      { key: "detail", label: "Event detail", kind: "textarea" },
      { key: "linkLabel", label: "Link label", kind: "text" },
      { key: "linkUrl", label: "Link URL", kind: "url" },
      surfaceField,
    ],
    defaultData: {
      eyebrow: "Event",
      status: "Planned",
      title: "Event title",
      body: "",
      eventTitle: "",
      meta: "",
      detail: "",
      linkLabel: "",
      linkUrl: "",
      surface: false,
    },
  },
  {
    type: "people_grid",
    label: "People",
    description: "Founders, Board, committees or faculty in a responsive grid.",
    fields: [
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "intro", label: "Introductory text", kind: "textarea" },
      {
        key: "people",
        label: "People",
        kind: "item_list",
        itemFields: [
          { key: "name", label: "Name", kind: "text" },
          { key: "role", label: "Role", kind: "text" },
          { key: "summary", label: "Profile", kind: "textarea" },
          { key: "imageUrl", label: "Portrait URL", kind: "url" },
          { key: "imageAlt", label: "Portrait alternative text", kind: "text" },
          { key: "focusX", label: "Horizontal image focus (%)", kind: "number", defaultValue: 50 },
          { key: "focusY", label: "Vertical image focus (%)", kind: "number", defaultValue: 50 },
        ],
      },
      { key: "footer", label: "Footer note", kind: "textarea" },
      { key: "linkLabel", label: "Section link label", kind: "text" },
      { key: "linkUrl", label: "Section link URL", kind: "url" },
      surfaceField,
    ],
    defaultData: {
      eyebrow: "Leadership",
      title: "People",
      intro: "",
      people: [],
      footer: "",
      linkLabel: "",
      linkUrl: "",
      surface: false,
    },
  },
  {
    type: "management_profile",
    label: "Management profile",
    description: "A prominent profile for the operational management role.",
    fields: [
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Section title", kind: "text" },
      { key: "role", label: "Role", kind: "text" },
      { key: "name", label: "Name", kind: "text" },
      { key: "summary", label: "Profile", kind: "textarea" },
      { key: "imageUrl", label: "Portrait URL", kind: "url" },
      { key: "imageAlt", label: "Portrait alternative text", kind: "text" },
      { key: "focusX", label: "Horizontal image focus (%)", kind: "number", defaultValue: 50 },
      { key: "focusY", label: "Vertical image focus (%)", kind: "number", defaultValue: 50 },
      surfaceField,
    ],
    defaultData: {
      eyebrow: "Management",
      title: "Society management",
      role: "Managing Director",
      name: "",
      summary: "",
      imageUrl: "",
      imageAlt: "",
      surface: true,
    },
  },
  {
    type: "cta",
    label: "Call to action",
    description: "Short closing section with one action.",
    fields: [
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "body", label: "Text", kind: "textarea" },
      { key: "buttonLabel", label: "Button label", kind: "text" },
      { key: "buttonUrl", label: "Button URL", kind: "url" },
      surfaceField,
    ],
    defaultData: {
      eyebrow: "",
      title: "Next step",
      body: "",
      buttonLabel: "Learn more",
      buttonUrl: "/about",
      surface: false,
    },
  },
  {
    type: "form_split",
    label: "Text and form",
    description: "Editorial text beside the interest-registration or contact form.",
    fields: [
      {
        key: "formType",
        label: "Form",
        kind: "select",
        options: [
          { label: "Interest registration", value: "interest" },
          { label: "Contact enquiry", value: "contact" },
        ],
      },
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "body", label: "Text", kind: "textarea" },
      { key: "secondary", label: "Additional note", kind: "textarea" },
      { key: "anchor", label: "Section anchor", kind: "text" },
      surfaceField,
    ],
    defaultData: {
      formType: "interest",
      eyebrow: "",
      title: "Get in touch",
      body: "",
      secondary: "",
      anchor: "",
      surface: true,
    },
  },
  {
    type: "rich_sections",
    label: "Article sections",
    description: "Long-form legal, privacy or policy content split into titled sections.",
    fields: [
      { key: "status", label: "Optional status", kind: "text" },
      { key: "statusMessage", label: "Status message", kind: "textarea" },
      {
        key: "sections",
        label: "Sections",
        kind: "item_list",
        itemFields: [
          { key: "title", label: "Title", kind: "text" },
          { key: "body", label: "Text", kind: "textarea" },
        ],
      },
      surfaceField,
    ],
    defaultData: { status: "", statusMessage: "", sections: [], surface: false },
  },
  {
    type: "image_text",
    label: "Image and text",
    description: "Image beside a heading, text and optional link.",
    fields: [
      ...imageFields,
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "body", label: "Text", kind: "textarea" },
      { key: "linkLabel", label: "Link label", kind: "text" },
      {
        key: "imageSide",
        label: "Image position",
        kind: "select",
        options: [
          { label: "Left", value: "left" },
          { label: "Right", value: "right" },
        ],
      },
      surfaceField,
    ],
    defaultData: {
      imageUrl: "",
      imageAlt: "",
      caption: "",
      rightsHolder: "",
      linkUrl: "",
      eyebrow: "",
      title: "Image and text",
      body: "",
      linkLabel: "",
      imageSide: "left",
      surface: false,
    },
  },
  {
    type: "gallery",
    label: "Image gallery",
    description: "Responsive gallery with captions, alternative text and rights information.",
    fields: [
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "intro", label: "Introductory text", kind: "textarea" },
      { key: "images", label: "Images", kind: "item_list", itemFields: imageFields },
      surfaceField,
    ],
    defaultData: { eyebrow: "", title: "Gallery", intro: "", images: [], surface: false },
  },
  {
    type: "carousel",
    label: "Carousel",
    description: "Accessible carousel for images, programme highlights or featured content.",
    fields: [
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "intro", label: "Introductory text", kind: "textarea" },
      {
        key: "slides",
        label: "Slides",
        kind: "item_list",
        itemFields: [
          ...imageFields,
          { key: "title", label: "Slide title", kind: "text" },
          { key: "body", label: "Slide text", kind: "textarea" },
          { key: "linkLabel", label: "Link label", kind: "text" },
        ],
      },
      surfaceField,
    ],
    defaultData: { eyebrow: "", title: "Carousel", intro: "", slides: [], surface: false },
  },
  {
    type: "resource_list",
    label: "Resources",
    description: "Documents, videos, links and educational resources.",
    fields: [
      { key: "eyebrow", label: "Small label", kind: "text" },
      { key: "title", label: "Title", kind: "text" },
      { key: "intro", label: "Introductory text", kind: "textarea" },
      {
        key: "items",
        label: "Resources",
        kind: "item_list",
        itemFields: [
          { key: "title", label: "Title", kind: "text" },
          { key: "type", label: "Type", kind: "text" },
          { key: "description", label: "Description", kind: "textarea" },
          { key: "url", label: "URL", kind: "url" },
          { key: "date", label: "Date", kind: "text" },
        ],
      },
      surfaceField,
    ],
    defaultData: {
      eyebrow: "Resources",
      title: "Educational resources",
      intro: "",
      items: [],
      surface: false,
    },
  },
];

export const cmsBlockDefinitionMap = Object.fromEntries(
  cmsBlockDefinitions.map((definition) => [definition.type, definition]),
) as Record<CmsBlockType, CmsBlockDefinition>;

export function cloneDefaultBlockData(type: CmsBlockType) {
  return structuredClone(cmsBlockDefinitionMap[type].defaultData);
}

export { linkFields };
