/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EducationAndScienceRouteImport } from './routes/education-and-science'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDemoRouteImport } from './routes/admin/demo'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminRegisterRouteImport } from './routes/admin/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationAndScienceRoute = EducationAndScienceRouteImport.update({
  id: '/education-and-science',
  path: '/education-and-science',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemoRoute = AdminDemoRouteImport.update({
  id: '/admin/demo',
  path: '/admin/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/education-and-science': typeof EducationAndScienceRoute
  '/leadership': typeof LeadershipRoute
  '/legal': typeof LegalRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/admin/demo': typeof AdminDemoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/education-and-science': typeof EducationAndScienceRoute
  '/leadership': typeof LeadershipRoute
  '/legal': typeof LegalRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/admin/demo': typeof AdminDemoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/education-and-science': typeof EducationAndScienceRoute
  '/leadership': typeof LeadershipRoute
  '/legal': typeof LegalRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/admin/demo': typeof AdminDemoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/contact'
    | '/education-and-science'
    | '/leadership'
    | '/legal'
    | '/membership'
    | '/privacy'
    | '/admin/demo'
    | '/admin/login'
    | '/admin/register'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/contact'
    | '/education-and-science'
    | '/leadership'
    | '/legal'
    | '/membership'
    | '/privacy'
    | '/admin/demo'
    | '/admin/login'
    | '/admin/register'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/contact'
    | '/education-and-science'
    | '/leadership'
    | '/legal'
    | '/membership'
    | '/privacy'
    | '/admin/demo'
    | '/admin/login'
    | '/admin/register'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EducationAndScienceRoute: typeof EducationAndScienceRoute
  LeadershipRoute: typeof LeadershipRoute
  LegalRoute: typeof LegalRoute
  MembershipRoute: typeof MembershipRoute
  PrivacyRoute: typeof PrivacyRoute
  AdminDemoRoute: typeof AdminDemoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-and-science': {
      id: '/education-and-science'
      path: '/education-and-science'
      fullPath: '/education-and-science'
      preLoaderRoute: typeof EducationAndScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demo': {
      id: '/admin/demo'
      path: '/admin/demo'
      fullPath: '/admin/demo'
      preLoaderRoute: typeof AdminDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EducationAndScienceRoute: EducationAndScienceRoute,
  LeadershipRoute: LeadershipRoute,
  LegalRoute: LegalRoute,
  MembershipRoute: MembershipRoute,
  PrivacyRoute: PrivacyRoute,
  AdminDemoRoute: AdminDemoRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
